FROM eclipse-temurin:17-jdk-alpine
LABEL description="Jeus common api Application"
COPY target/jeus-echo-spring-1.0.jar /jeus-echo-spring-1.0.jar
ENTRYPOINT [ "java", "-jar", "/jeus-echo-spring-1.0.jar" ]